import { FlowNode, FlowEdge, CodeLanguage, FlowNodeData } from './types';

// ── Code Generator ──────────────────────────────────────────────────────────

export function generateCode(
  nodes: FlowNode[],
  edges: FlowEdge[],
  language: CodeLanguage,
  graphName: string
): string {
  if (language === 'python') {
    return generatePython(nodes, edges, graphName);
  }
  return generateTypeScript(nodes, edges, graphName);
}

// ── Python Generation ───────────────────────────────────────────────────────

function generatePython(nodes: FlowNode[], edges: FlowEdge[], graphName: string): string {
  const lines: string[] = [];
  const sortedNodes = topologicalSort(nodes, edges);
  const indent = '    ';

  lines.push('"""');
  lines.push(`${graphName} - Generated by FlowGraph`);
  lines.push('"""');
  lines.push('');
  lines.push('import asyncio');
  lines.push('import json');
  lines.push('from typing import Any, Dict, Optional');
  lines.push('from dataclasses import dataclass, field');
  lines.push('');
  lines.push('');
  lines.push('@dataclass');
  lines.push('class AgentState:');
  lines.push(`${indent}"""Holds the workflow execution state."""`);
  lines.push(`${indent}variables: Dict[str, Any] = field(default_factory=dict)`);
  lines.push(`${indent}current_input: Any = None`);
  lines.push(`${indent}log: list = field(default_factory=list)`);
  lines.push('');
  lines.push('');

  // Generate node functions
  for (const nodeId of sortedNodes) {
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) continue;
    lines.push(...generatePythonNodeFunction(node, indent));
    lines.push('');
    lines.push('');
  }

  // Generate main orchestrator
  lines.push(`async def run_${sanitizeName(graphName)}(initial_input: Any = None) -> Dict[str, Any]:`);
  lines.push(`${indent}"""Execute the ${graphName} workflow."""`);
  lines.push(`${indent}state = AgentState(current_input=initial_input)`);
  lines.push('');

  for (const nodeId of sortedNodes) {
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) continue;
    const funcName = nodeFuncName(node);
    const incoming = edges.filter((e) => e.target === nodeId);

    if (incoming.length === 1) {
      lines.push(`${indent}# ${node.data.label}`);
      lines.push(`${indent}state.current_input = state.variables.get("${incoming[0].source}_output")`);
    } else if (incoming.length > 1) {
      lines.push(`${indent}# ${node.data.label} (merged inputs)`);
      const inputDict = incoming.map((e) => `"${e.source}": state.variables.get("${e.source}_output")`).join(', ');
      lines.push(`${indent}state.current_input = {${inputDict}}`);
    } else {
      lines.push(`${indent}# ${node.data.label}`);
    }

    if (node.data.nodeType === 'branch') {
      lines.push(`${indent}branch_result = await ${funcName}(state)`);
      lines.push(`${indent}state.variables["${nodeId}_output"] = branch_result`);
    } else {
      lines.push(`${indent}result = await ${funcName}(state)`);
      lines.push(`${indent}state.variables["${nodeId}_output"] = result`);
    }
    lines.push('');
  }

  lines.push(`${indent}return state.variables`);
  lines.push('');
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push(`${indent}result = asyncio.run(run_${sanitizeName(graphName)}())`);
  lines.push(`${indent}print(json.dumps(result, indent=2, default=str))`);

  return lines.join('\n');
}

function generatePythonNodeFunction(node: FlowNode, indent: string): string[] {
  const lines: string[] = [];
  const funcName = nodeFuncName(node);
  const data = node.data;

  lines.push(`async def ${funcName}(state: AgentState) -> Any:`);
  lines.push(`${indent}"""${data.description || data.label}"""`);

  switch (data.nodeType) {
    case 'start':
      lines.push(`${indent}return {"started": True, "input": state.current_input}`);
      break;

    case 'llm': {
      const config = data.config as { model: string; systemPrompt: string; temperature: number; maxTokens: number };
      lines.push(`${indent}# Configure your LLM client here`);
      lines.push(`${indent}model = "${config.model}"`);
      lines.push(`${indent}system_prompt = """${config.systemPrompt}"""`);
      lines.push(`${indent}temperature = ${config.temperature}`);
      lines.push(`${indent}max_tokens = ${config.maxTokens}`);
      lines.push('');
      lines.push(`${indent}# Example with OpenAI client:`);
      lines.push(`${indent}# from openai import AsyncOpenAI`);
      lines.push(`${indent}# client = AsyncOpenAI()`);
      lines.push(`${indent}# response = await client.chat.completions.create(`);
      lines.push(`${indent}#     model=model,`);
      lines.push(`${indent}#     messages=[`);
      lines.push(`${indent}#         {"role": "system", "content": system_prompt},`);
      lines.push(`${indent}#         {"role": "user", "content": str(state.current_input)}`);
      lines.push(`${indent}#     ],`);
      lines.push(`${indent}#     temperature=temperature,`);
      lines.push(`${indent}#     max_tokens=max_tokens`);
      lines.push(`${indent}# )`);
      lines.push(`${indent}# return response.choices[0].message.content`);
      lines.push(`${indent}raise NotImplementedError("Connect your LLM provider")`);
      break;
    }

    case 'tool': {
      const config = data.config as { toolName: string; endpoint: string; method: string; bodyTemplate: string };
      lines.push(`${indent}import aiohttp`);
      lines.push('');
      lines.push(`${indent}url = "${config.endpoint}"`);
      lines.push(`${indent}method = "${config.method}"`);
      lines.push(`${indent}body_template = '${config.bodyTemplate}'`);
      lines.push(`${indent}body = body_template.replace("{{input}}", json.dumps(state.current_input, default=str))`);
      lines.push('');
      lines.push(`${indent}async with aiohttp.ClientSession() as session:`);
      lines.push(`${indent}${indent}async with session.request(method, url, data=body, headers={"Content-Type": "application/json"}) as resp:`);
      lines.push(`${indent}${indent}${indent}return await resp.json()`);
      break;
    }

    case 'branch': {
      const config = data.config as { conditions: Array<{ label: string; expression: string }> };
      for (let i = 0; i < config.conditions.length; i++) {
        const cond = config.conditions[i];
        if (cond.expression === 'default') {
          lines.push(`${indent}${i === 0 ? '' : 'else'}:`);
          lines.push(`${indent}${indent}return {"branch": "${cond.label}", "input": state.current_input}`);
        } else {
          const keyword = i === 0 ? 'if' : 'elif';
          lines.push(`${indent}${keyword} ${pythonifyExpression(cond.expression)}:`);
          lines.push(`${indent}${indent}return {"branch": "${cond.label}", "input": state.current_input}`);
        }
      }
      break;
    }

    case 'loop': {
      const config = data.config as { loopType: string; iteratorExpression: string; maxIterations: number };
      lines.push(`${indent}results = []`);
      lines.push(`${indent}items = ${pythonifyExpression(config.iteratorExpression)} or []`);
      lines.push(`${indent}max_iterations = ${config.maxIterations}`);
      lines.push('');
      lines.push(`${indent}for i, item in enumerate(items[:max_iterations]):`);
      lines.push(`${indent}${indent}# Process each item`);
      lines.push(`${indent}${indent}results.append({"index": i, "item": item})`);
      lines.push('');
      lines.push(`${indent}return {"iterations": len(results), "results": results}`);
      break;
    }

    case 'transform': {
      const config = data.config as { transformExpression: string };
      lines.push(`${indent}input_data = state.current_input`);
      lines.push(`${indent}# Transform expression: ${config.transformExpression}`);
      lines.push(`${indent}return {**input_data, "transformed": True} if isinstance(input_data, dict) else input_data`);
      break;
    }

    case 'merge':
      lines.push(`${indent}return state.current_input`);
      break;

    case 'input':
      lines.push(`${indent}return state.current_input or ${JSON.stringify(data.config.defaultValues || {})}`);
      break;

    case 'output':
      lines.push(`${indent}return {"result": state.current_input}`);
      break;

    case 'delay': {
      const config = data.config as { delayMs: number };
      lines.push(`${indent}await asyncio.sleep(${config.delayMs / 1000})`);
      lines.push(`${indent}return state.current_input`);
      break;
    }

    case 'error-handler': {
      const config = data.config as { retryCount: number; retryDelayMs: number };
      lines.push(`${indent}for attempt in range(${config.retryCount}):`);
      lines.push(`${indent}${indent}try:`);
      lines.push(`${indent}${indent}${indent}return state.current_input`);
      lines.push(`${indent}${indent}except Exception as e:`);
      lines.push(`${indent}${indent}${indent}if attempt == ${config.retryCount - 1}:`);
      lines.push(`${indent}${indent}${indent}${indent}return {"error": str(e), "fallback": True}`);
      lines.push(`${indent}${indent}${indent}await asyncio.sleep(${config.retryDelayMs / 1000})`);
      break;
    }

    default:
      lines.push(`${indent}return state.current_input`);
  }

  return lines;
}

// ── TypeScript Generation ───────────────────────────────────────────────────

function generateTypeScript(nodes: FlowNode[], edges: FlowEdge[], graphName: string): string {
  const lines: string[] = [];
  const sortedNodes = topologicalSort(nodes, edges);
  const indent = '  ';

  lines.push(`/**`);
  lines.push(` * ${graphName} - Generated by FlowGraph`);
  lines.push(` */`);
  lines.push('');
  lines.push('interface AgentState {');
  lines.push(`${indent}variables: Record<string, unknown>;`);
  lines.push(`${indent}currentInput: unknown;`);
  lines.push(`${indent}log: Array<{ node: string; status: string; output: unknown }>;`);
  lines.push('}');
  lines.push('');

  // Generate node functions
  for (const nodeId of sortedNodes) {
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) continue;
    lines.push(...generateTSNodeFunction(node, indent));
    lines.push('');
  }

  // Generate main orchestrator
  const funcName = sanitizeName(graphName);
  lines.push(`export async function run${capitalize(funcName)}(initialInput?: unknown): Promise<Record<string, unknown>> {`);
  lines.push(`${indent}const state: AgentState = {`);
  lines.push(`${indent}${indent}variables: {},`);
  lines.push(`${indent}${indent}currentInput: initialInput ?? null,`);
  lines.push(`${indent}${indent}log: [],`);
  lines.push(`${indent}};`);
  lines.push('');

  for (const nodeId of sortedNodes) {
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) continue;
    const fnName = nodeFuncName(node);
    const incoming = edges.filter((e) => e.target === nodeId);

    if (incoming.length === 1) {
      lines.push(`${indent}// ${node.data.label}`);
      lines.push(`${indent}state.currentInput = state.variables["${incoming[0].source}_output"];`);
    } else if (incoming.length > 1) {
      lines.push(`${indent}// ${node.data.label} (merged inputs)`);
      const entries = incoming.map((e) => `"${e.source}": state.variables["${e.source}_output"]`).join(', ');
      lines.push(`${indent}state.currentInput = { ${entries} };`);
    } else {
      lines.push(`${indent}// ${node.data.label}`);
    }

    lines.push(`${indent}state.variables["${nodeId}_output"] = await ${fnName}(state);`);
    lines.push('');
  }

  lines.push(`${indent}return state.variables;`);
  lines.push('}');
  lines.push('');
  lines.push('// Run');
  lines.push(`run${capitalize(funcName)}().then((result) => console.log(JSON.stringify(result, null, 2)));`);

  return lines.join('\n');
}

function generateTSNodeFunction(node: FlowNode, indent: string): string[] {
  const lines: string[] = [];
  const funcName = nodeFuncName(node);
  const data = node.data;

  lines.push(`async function ${funcName}(state: AgentState): Promise<unknown> {`);

  switch (data.nodeType) {
    case 'start':
      lines.push(`${indent}return { started: true, input: state.currentInput };`);
      break;

    case 'llm': {
      const config = data.config as { model: string; systemPrompt: string; temperature: number; maxTokens: number };
      lines.push(`${indent}// Configure your LLM client here`);
      lines.push(`${indent}const model = "${config.model}";`);
      lines.push(`${indent}const systemPrompt = \`${config.systemPrompt}\`;`);
      lines.push(`${indent}const temperature = ${config.temperature};`);
      lines.push(`${indent}const maxTokens = ${config.maxTokens};`);
      lines.push('');
      lines.push(`${indent}// Example with OpenAI:`);
      lines.push(`${indent}// const response = await openai.chat.completions.create({`);
      lines.push(`${indent}//   model, messages: [{ role: "system", content: systemPrompt }, { role: "user", content: String(state.currentInput) }],`);
      lines.push(`${indent}//   temperature, max_tokens: maxTokens,`);
      lines.push(`${indent}// });`);
      lines.push(`${indent}// return response.choices[0].message.content;`);
      lines.push(`${indent}throw new Error("Connect your LLM provider");`);
      break;
    }

    case 'tool': {
      const config = data.config as { endpoint: string; method: string; bodyTemplate: string };
      lines.push(`${indent}const url = "${config.endpoint}";`);
      lines.push(`${indent}const body = '${config.bodyTemplate}'.replace("{{input}}", JSON.stringify(state.currentInput));`);
      lines.push('');
      lines.push(`${indent}const response = await fetch(url, {`);
      lines.push(`${indent}${indent}method: "${config.method}",`);
      lines.push(`${indent}${indent}headers: { "Content-Type": "application/json" },`);
      lines.push(`${indent}${indent}body,`);
      lines.push(`${indent}});`);
      lines.push(`${indent}return response.json();`);
      break;
    }

    case 'branch': {
      const config = data.config as { conditions: Array<{ label: string; expression: string }> };
      for (let i = 0; i < config.conditions.length; i++) {
        const cond = config.conditions[i];
        if (cond.expression === 'default') {
          lines.push(`${indent}return { branch: "${cond.label}", input: state.currentInput };`);
        } else {
          const keyword = i === 0 ? 'if' : 'else if';
          lines.push(`${indent}${keyword} (${cond.expression.replace(/input/g, 'state.currentInput as any')}) {`);
          lines.push(`${indent}${indent}return { branch: "${cond.label}", input: state.currentInput };`);
          lines.push(`${indent}}`);
        }
      }
      break;
    }

    case 'loop': {
      const config = data.config as { maxIterations: number };
      lines.push(`${indent}const items = Array.isArray(state.currentInput) ? state.currentInput : [];`);
      lines.push(`${indent}const results = [];`);
      lines.push(`${indent}const maxIter = ${config.maxIterations};`);
      lines.push('');
      lines.push(`${indent}for (let i = 0; i < Math.min(items.length, maxIter); i++) {`);
      lines.push(`${indent}${indent}results.push({ index: i, item: items[i] });`);
      lines.push(`${indent}}`);
      lines.push(`${indent}return { iterations: results.length, results };`);
      break;
    }

    case 'transform': {
      const config = data.config as { transformExpression: string };
      lines.push(`${indent}const input = state.currentInput;`);
      lines.push(`${indent}${config.transformExpression}`);
      break;
    }

    case 'merge':
      lines.push(`${indent}return state.currentInput;`);
      break;

    case 'input':
      lines.push(`${indent}return state.currentInput ?? ${JSON.stringify(data.config.defaultValues || {})};`);
      break;

    case 'output':
      lines.push(`${indent}return { result: state.currentInput };`);
      break;

    case 'delay': {
      const config = data.config as { delayMs: number };
      lines.push(`${indent}await new Promise((r) => setTimeout(r, ${config.delayMs}));`);
      lines.push(`${indent}return state.currentInput;`);
      break;
    }

    case 'error-handler': {
      const config = data.config as { retryCount: number; retryDelayMs: number };
      lines.push(`${indent}for (let attempt = 0; attempt < ${config.retryCount}; attempt++) {`);
      lines.push(`${indent}${indent}try {`);
      lines.push(`${indent}${indent}${indent}return state.currentInput;`);
      lines.push(`${indent}${indent}} catch (e) {`);
      lines.push(`${indent}${indent}${indent}if (attempt === ${config.retryCount - 1}) return { error: String(e), fallback: true };`);
      lines.push(`${indent}${indent}${indent}await new Promise((r) => setTimeout(r, ${config.retryDelayMs}));`);
      lines.push(`${indent}${indent}}`);
      lines.push(`${indent}}`);
      break;
    }

    default:
      lines.push(`${indent}return state.currentInput;`);
  }

  lines.push('}');
  return lines;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function topologicalSort(nodes: FlowNode[], edges: FlowEdge[]): string[] {
  const inDegree: Record<string, number> = {};
  const adjacency: Record<string, string[]> = {};

  for (const node of nodes) {
    inDegree[node.id] = 0;
    adjacency[node.id] = [];
  }
  for (const edge of edges) {
    if (adjacency[edge.source]) adjacency[edge.source].push(edge.target);
    if (inDegree[edge.target] !== undefined) inDegree[edge.target]++;
  }

  const queue: string[] = Object.keys(inDegree).filter((id) => inDegree[id] === 0);
  queue.sort((a, b) => {
    const nA = nodes.find((n) => n.id === a);
    const nB = nodes.find((n) => n.id === b);
    if (nA?.data.nodeType === 'start') return -1;
    if (nB?.data.nodeType === 'start') return 1;
    return 0;
  });

  const result: string[] = [];
  while (queue.length > 0) {
    const current = queue.shift()!;
    result.push(current);
    for (const neighbor of adjacency[current] || []) {
      inDegree[neighbor]--;
      if (inDegree[neighbor] === 0) queue.push(neighbor);
    }
  }
  return result;
}

function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function nodeFuncName(node: FlowNode): string {
  const base = sanitizeName(node.data.label);
  const short = node.id.substring(0, 6);
  return `${base}_${short}`;
}

function pythonifyExpression(expr: string): string {
  return expr
    .replace(/\./g, '.')
    .replace(/===/g, '==')
    .replace(/!==/g, '!=')
    .replace(/true/gi, 'True')
    .replace(/false/gi, 'False')
    .replace(/null/gi, 'None')
    .replace(/undefined/gi, 'None');
}
