import { GraphTemplate } from './types';

export const GRAPH_TEMPLATES: GraphTemplate[] = [
  {
    id: 'simple-chatbot',
    name: 'Simple Chatbot',
    description: 'A basic chatbot that takes user input, sends it to an LLM, and returns the response.',
    category: 'Basics',
    tags: ['chatbot', 'llm', 'beginner'],
    thumbnail: 'MessageSquare',
    nodes: [
      {
        id: 'start-1',
        type: 'custom-start',
        position: { x: 100, y: 200 },
        data: {
          label: 'Start',
          description: 'Entry point',
          nodeType: 'start',
          config: {},
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'input-1',
        type: 'custom-input',
        position: { x: 350, y: 200 },
        data: {
          label: 'User Message',
          description: 'Get user input',
          nodeType: 'input',
          config: {
            inputSchema: { message: 'string' },
            defaultValues: { message: 'Hello, how are you?' },
          },
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'llm-1',
        type: 'custom-llm',
        position: { x: 600, y: 200 },
        data: {
          label: 'Chat LLM',
          description: 'Process with language model',
          nodeType: 'llm',
          config: {
            model: 'gpt-4',
            systemPrompt: 'You are a friendly and helpful chatbot assistant.',
            temperature: 0.7,
            maxTokens: 512,
            inputMapping: '{{input}}',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'output-1',
        type: 'custom-output',
        position: { x: 850, y: 200 },
        data: {
          label: 'Response',
          description: 'Return chatbot response',
          nodeType: 'output',
          config: { outputMapping: 'input', format: 'text' },
          ports: [{ id: 'in', label: 'Input', type: 'input' }],
          breakpoint: false,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'input-1', type: 'smoothstep', animated: false, style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e2', source: 'input-1', target: 'llm-1', type: 'smoothstep', animated: false, style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e3', source: 'llm-1', target: 'output-1', type: 'smoothstep', animated: false, style: { stroke: '#6366f1', strokeWidth: 2 } },
    ],
  },
  {
    id: 'rag-pipeline',
    name: 'RAG Pipeline',
    description: 'Retrieval-Augmented Generation pipeline that searches a knowledge base and augments LLM responses.',
    category: 'Advanced',
    tags: ['rag', 'retrieval', 'search', 'llm'],
    thumbnail: 'Search',
    nodes: [
      {
        id: 'start-1',
        type: 'custom-start',
        position: { x: 100, y: 250 },
        data: {
          label: 'Start',
          description: 'Entry point',
          nodeType: 'start',
          config: {},
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'input-1',
        type: 'custom-input',
        position: { x: 350, y: 250 },
        data: {
          label: 'User Query',
          description: 'Receive search query',
          nodeType: 'input',
          config: {
            inputSchema: { query: 'string' },
            defaultValues: { query: 'What is retrieval augmented generation?' },
          },
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'tool-embed',
        type: 'custom-tool',
        position: { x: 600, y: 150 },
        data: {
          label: 'Embed Query',
          description: 'Generate embeddings for the query',
          nodeType: 'tool',
          config: {
            toolName: 'embeddings',
            endpoint: 'https://api.openai.com/v1/embeddings',
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            bodyTemplate: '{"input": "{{input}}", "model": "text-embedding-3-small"}',
            outputMapping: 'data[0].embedding',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'tool-search',
        type: 'custom-tool',
        position: { x: 850, y: 150 },
        data: {
          label: 'Vector Search',
          description: 'Search knowledge base',
          nodeType: 'tool',
          config: {
            toolName: 'vector_search',
            endpoint: 'https://your-db.supabase.co/rest/v1/rpc/match_documents',
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            bodyTemplate: '{"query_embedding": "{{input}}", "match_count": 5}',
            outputMapping: 'response',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'transform-1',
        type: 'custom-transform',
        position: { x: 850, y: 350 },
        data: {
          label: 'Build Context',
          description: 'Combine query with retrieved documents',
          nodeType: 'transform',
          config: {
            transformExpression: 'return { query: input.query, context: input.documents.map(d => d.content).join("\\n") };',
            language: 'javascript',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'llm-1',
        type: 'custom-llm',
        position: { x: 1100, y: 250 },
        data: {
          label: 'Generate Answer',
          description: 'Generate answer with context',
          nodeType: 'llm',
          config: {
            model: 'gpt-4',
            systemPrompt: 'Answer the user question using only the provided context. If the context does not contain the answer, say so.',
            temperature: 0.3,
            maxTokens: 1024,
            inputMapping: '{{input}}',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'output-1',
        type: 'custom-output',
        position: { x: 1350, y: 250 },
        data: {
          label: 'Answer',
          description: 'Final answer',
          nodeType: 'output',
          config: { outputMapping: 'input', format: 'markdown' },
          ports: [{ id: 'in', label: 'Input', type: 'input' }],
          breakpoint: false,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'input-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e2', source: 'input-1', target: 'tool-embed', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e3', source: 'tool-embed', target: 'tool-search', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e4', source: 'tool-search', target: 'transform-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e5', source: 'transform-1', target: 'llm-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e6', source: 'llm-1', target: 'output-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
    ],
  },
  {
    id: 'routing-agent',
    name: 'Routing Agent',
    description: 'An agent that classifies user intent and routes to different processing pipelines.',
    category: 'Agents',
    tags: ['agent', 'routing', 'classification', 'branch'],
    thumbnail: 'GitBranch',
    nodes: [
      {
        id: 'start-1',
        type: 'custom-start',
        position: { x: 100, y: 300 },
        data: {
          label: 'Start',
          description: 'Entry point',
          nodeType: 'start',
          config: {},
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'input-1',
        type: 'custom-input',
        position: { x: 350, y: 300 },
        data: {
          label: 'User Request',
          description: 'Receive user request',
          nodeType: 'input',
          config: {
            inputSchema: { request: 'string' },
            defaultValues: { request: 'Book a flight to Tokyo' },
          },
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'llm-classify',
        type: 'custom-llm',
        position: { x: 600, y: 300 },
        data: {
          label: 'Classify Intent',
          description: 'Classify user intent',
          nodeType: 'llm',
          config: {
            model: 'gpt-4',
            systemPrompt: 'Classify the user intent into: booking, question, complaint, or other. Respond with just the category.',
            temperature: 0,
            maxTokens: 50,
            inputMapping: '{{input}}',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'branch-1',
        type: 'custom-branch',
        position: { x: 850, y: 300 },
        data: {
          label: 'Route by Intent',
          description: 'Route based on classification',
          nodeType: 'branch',
          config: {
            conditions: [
              { id: 'c1', label: 'Booking', expression: 'input.intent === "booking"', targetHandle: 'true' },
              { id: 'c2', label: 'Other', expression: 'default', targetHandle: 'false' },
            ],
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'true', label: 'Booking', type: 'output' },
            { id: 'false', label: 'Other', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'llm-booking',
        type: 'custom-llm',
        position: { x: 1100, y: 200 },
        data: {
          label: 'Booking Agent',
          description: 'Handle booking requests',
          nodeType: 'llm',
          config: {
            model: 'gpt-4',
            systemPrompt: 'You are a booking assistant. Help the user with their booking request.',
            temperature: 0.5,
            maxTokens: 512,
            inputMapping: '{{input}}',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'llm-general',
        type: 'custom-llm',
        position: { x: 1100, y: 400 },
        data: {
          label: 'General Agent',
          description: 'Handle general requests',
          nodeType: 'llm',
          config: {
            model: 'gpt-4',
            systemPrompt: 'You are a helpful general assistant.',
            temperature: 0.7,
            maxTokens: 512,
            inputMapping: '{{input}}',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'merge-1',
        type: 'custom-merge',
        position: { x: 1350, y: 300 },
        data: {
          label: 'Merge Responses',
          description: 'Merge agent responses',
          nodeType: 'merge',
          config: { strategy: 'first', mergeExpression: '' },
          ports: [
            { id: 'in-1', label: 'Input 1', type: 'input' },
            { id: 'in-2', label: 'Input 2', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'output-1',
        type: 'custom-output',
        position: { x: 1600, y: 300 },
        data: {
          label: 'Response',
          description: 'Final response',
          nodeType: 'output',
          config: { outputMapping: 'input', format: 'text' },
          ports: [{ id: 'in', label: 'Input', type: 'input' }],
          breakpoint: false,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'input-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e2', source: 'input-1', target: 'llm-classify', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e3', source: 'llm-classify', target: 'branch-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e4', source: 'branch-1', target: 'llm-booking', sourceHandle: 'true', type: 'smoothstep', style: { stroke: '#22c55e', strokeWidth: 2 } },
      { id: 'e5', source: 'branch-1', target: 'llm-general', sourceHandle: 'false', type: 'smoothstep', style: { stroke: '#f59e0b', strokeWidth: 2 } },
      { id: 'e6', source: 'llm-booking', target: 'merge-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e7', source: 'llm-general', target: 'merge-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e8', source: 'merge-1', target: 'output-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
    ],
  },
  {
    id: 'data-processing',
    name: 'Data Processing Pipeline',
    description: 'Process a list of items with transformation, error handling, and aggregation.',
    category: 'Data',
    tags: ['loop', 'transform', 'error-handling', 'data'],
    thumbnail: 'Database',
    nodes: [
      {
        id: 'start-1',
        type: 'custom-start',
        position: { x: 100, y: 250 },
        data: {
          label: 'Start',
          description: 'Entry point',
          nodeType: 'start',
          config: {},
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'input-1',
        type: 'custom-input',
        position: { x: 350, y: 250 },
        data: {
          label: 'Data Source',
          description: 'Input data to process',
          nodeType: 'input',
          config: {
            inputSchema: { items: 'array' },
            defaultValues: { items: [1, 2, 3, 4, 5] },
          },
          ports: [{ id: 'out', label: 'Output', type: 'output' }],
          breakpoint: false,
        },
      },
      {
        id: 'loop-1',
        type: 'custom-loop',
        position: { x: 600, y: 250 },
        data: {
          label: 'Process Items',
          description: 'Loop over each item',
          nodeType: 'loop',
          config: {
            loopType: 'forEach',
            iteratorExpression: 'input.items',
            maxIterations: 100,
            breakCondition: '',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'body', label: 'Loop Body', type: 'output' },
            { id: 'done', label: 'Done', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'transform-1',
        type: 'custom-transform',
        position: { x: 850, y: 150 },
        data: {
          label: 'Transform Item',
          description: 'Transform each item',
          nodeType: 'transform',
          config: {
            transformExpression: 'return { ...input, value: input.value * 2, processed: true };',
            language: 'javascript',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Output', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'error-1',
        type: 'custom-error-handler',
        position: { x: 850, y: 350 },
        data: {
          label: 'Error Handler',
          description: 'Handle processing errors',
          nodeType: 'error-handler',
          config: {
            retryCount: 3,
            retryDelayMs: 1000,
            fallbackExpression: '{ "error": true, "skipped": true }',
            catchPattern: '*',
          },
          ports: [
            { id: 'in', label: 'Input', type: 'input' },
            { id: 'out', label: 'Success', type: 'output' },
            { id: 'error', label: 'Error', type: 'output' },
          ],
          breakpoint: false,
        },
      },
      {
        id: 'output-1',
        type: 'custom-output',
        position: { x: 1100, y: 250 },
        data: {
          label: 'Results',
          description: 'Aggregated results',
          nodeType: 'output',
          config: { outputMapping: 'input', format: 'json' },
          ports: [{ id: 'in', label: 'Input', type: 'input' }],
          breakpoint: false,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'input-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e2', source: 'input-1', target: 'loop-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e3', source: 'loop-1', target: 'transform-1', sourceHandle: 'body', type: 'smoothstep', style: { stroke: '#06b6d4', strokeWidth: 2 } },
      { id: 'e4', source: 'transform-1', target: 'error-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
      { id: 'e5', source: 'loop-1', target: 'output-1', sourceHandle: 'done', type: 'smoothstep', style: { stroke: '#22c55e', strokeWidth: 2 } },
      { id: 'e6', source: 'error-1', target: 'output-1', type: 'smoothstep', style: { stroke: '#6366f1', strokeWidth: 2 } },
    ],
  },
];
